/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import abstratas.Dados;
import classes.Cliente;
import classes.Equipamento;
import classes.Tecnico;
import enuns.Especialidades;

/**
 *
 * @author murilo.fernandes
 */
public class frameManu extends javax.swing.JFrame {

    /**
     * Creates new form frameManu
     */
    public frameManu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        itemTecnicos = new javax.swing.JMenuItem();
        itemEquipamentos = new javax.swing.JMenuItem();
        itemOrdemServico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordem de Serviço");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMenu1.setText("Arquivos");

        itemClientes.setText("Clientes");
        itemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClientesActionPerformed(evt);
            }
        });
        jMenu1.add(itemClientes);

        itemTecnicos.setText("Tecnicos");
        itemTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTecnicosActionPerformed(evt);
            }
        });
        jMenu1.add(itemTecnicos);

        itemEquipamentos.setText("Equipamentos");
        itemEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEquipamentosActionPerformed(evt);
            }
        });
        jMenu1.add(itemEquipamentos);

        itemOrdemServico.setText("Ordem de Serviço");
        itemOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrdemServicoActionPerformed(evt);
            }
        });
        jMenu1.add(itemOrdemServico);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTecnicosActionPerformed
        // TODO add your handling code here:
        
        new dialogTecnico(this, true).setVisible(true);
    }//GEN-LAST:event_itemTecnicosActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        // TODO add your handling code here:
        
        new dialogCliente(this, true).setVisible(true);
    }//GEN-LAST:event_itemClientesActionPerformed

    private void itemEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEquipamentosActionPerformed
        // TODO add your handling code here:
        new dialogEquipamento(this, true).setVisible(true);
    }//GEN-LAST:event_itemEquipamentosActionPerformed

    private void itemOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrdemServicoActionPerformed
        // TODO add your handling code here:
        new dialogServico(this, true).setVisible(true);
    }//GEN-LAST:event_itemOrdemServicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //popular lista de clientes
        Cliente cliente0 = new Cliente("Murilo", "071.775.319-04", "(048)99677-2239","Rua alicio castelan");
        Cliente cliente1 = new Cliente("camila", "071.777.319-04", "(048)99402-2239","Rua alicio castelan");
        Cliente cliente2 = new Cliente("brino", "071.790.319-04", "(048)99677-7239","xxxxxxxxx");
        Cliente cliente3 = new Cliente("aiiii", "071.775.319-04", "(048)99677-2239","Rua alicio castelan");
        
        Dados.getListaCliente().add(cliente0);
        Dados.getListaCliente().add(cliente1);
        Dados.getListaCliente().add(cliente2);
        Dados.getListaCliente().add(cliente3);
        
        //popular lista de tecnicos
        Tecnico tecnico1 = new Tecnico("camilaaaa", "071.312.212-01", "(99)99999-9999" , 4000.00, Especialidades.C);
        
        Dados.getListaTecnico().add(tecnico1);
        
        //popular lista de equipamentos.
        Equipamento equipamento = new Equipamento("S22", "Celular", cliente0);
        
        Dados.getListaEquipamento().add(equipamento);
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameManu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameManu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameManu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameManu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameManu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemEquipamentos;
    private javax.swing.JMenuItem itemOrdemServico;
    private javax.swing.JMenuItem itemTecnicos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
